version: "2"
prepare:
  fetch: 
    - "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 5
  file-lines:
    enabled: true
    config:
      threshold: 250
  identical-code:
    enabled: true
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: false
  method-lines:
    enabled: true
    config:
      threshold: 10
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
  similar-code:
    enabled: true

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
  checkstyle:
    enabled: true
    config:
      file: "google_checks.xml"
