authenticationMode: TEST
testUrl:
   baseUrl: ${BASE_URL}
   perryLoginUrl: ${PERRY_LOGIN_URL}
   authLoginUrl: ${AUTH_LOGIN_URL}
   tokenUrl: ${TOKEN_URL}
   callBackUrl: ${CALL_BACK_URL}
   logOutUrl: ${LOG_OUT_URL}
   validateUrl: ${VALIDATE_URL}
defaultUsers:
    -  userType: socialWorkerOnly
       username: '{ "user": "RACFID", "staffId": "0X5", "roles": [ "Supervisor" ], "county_code": "56", "county_cws_code": "1123", "county_name": "Ventura", "privileges": [ "CWS Case Management System", "Resource Management", "Resource Mgmt Placement Facility Maint", "Sealed", "Sensitive Persons" ] }'
       password: ${PASSWORD:-}
    -  userType: countySensitivePrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
    -  userType: countySealedPrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
    -  userType: stateSensitivePrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
    -  userType: stateSealedPrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}