authenticationMode: TEST
testUrl:
   baseUrl: ${BASE_URL:-https://ferbapi.preint.cwds.io}
   perryLoginUrl: ${PERRY_LOGIN_URL:-https://localhost:8090/perry/login}
   authLoginUrl: ${AUTH_LOGIN_URL:-https://localhost:8090/perry/authn/login}
   tokenUrl: ${TOKEN_URL:-https://localhost:8090/perry/authn/token}
   callBackUrl: ${CALL_BACK_URL:-https://ferbapi.preint.cwds.io/swagger}
   logOutUrl: ${LOG_OUT_URL:-}
   validateUrl: ${VALIDATE_URL:-https://localhost:8090/perry/authn/validate}
   
defaultUsers:
    -  userType: socialWorkerOnly
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
       
    -  userType: countySensitivePrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}  
        
    -  userType: countySealedPrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-} 
       
    -  userType: stateSensitivePrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
       
    -  userType: stateSealedPrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
